# Generated by Django 5.2 on 2025-08-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_user', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_year', models.DateField(blank=True, null=True)),
                ('ddd_user', models.IntegerField(blank=True, null=True)),
                ('number_user', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
