# Generated by Django 5.2 on 2025-05-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
